### ISSUE TITLE
Bring configuration into react-sapling

### ISSUE THREAD

**Issue by trevorsenior** [willowtreeapps/react-sapling#72]
With much sadness, configuration is coming to this project on the condition that the configuration is **always** opt-in vs. a hard requirement. 

A new optional `"sapling"` object will be added to package.json and support the fields:

- [ ] `"test-runner"`: `"jest"` _or_ `"karma"` **DEFAULT**: `"karma"` (See #51)
- [ ] `"root-style-path"`: <path to root styles scss> **DEFAULT**: use styles baked in react-sapling  (See #15) 
- [ ] `"dev-port"`: <number> **DEFAULT**: 5400  (See #67)
